apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
data:
  application.properties: |
    welcome.message = "Hello, World. From ConfigMap"