kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "demo.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "demo.fullname" . }}
  apiGroup: ""